require 'test_helper'

class LaunchControllerTest < ActionController::TestCase
  good_json = {"oauth_consumer_key"=>"1", "oauth_signature_method"=>"HMAC-SHA1", "oauth_timestamp"=>"1470694948", "oauth_nonce"=>"n4u2xXQsdfDgsQbmF1YWTCzj8zCIsu3nDvdWxisbo", "oauth_version"=>"1.0", "context_id"=>"b1777b696e0fb3ce80bf363f68caa2b2e2f1fb29", "context_label"=>"asdfasdf", "context_title"=>"stupid_course", "custom_canvas_api_domain"=>"jpoulos.instructure.com", "custom_canvas_course_id"=>"837", "custom_canvas_enrollment_state"=>"", "custom_canvas_user_id"=>"170000004596788", "custom_canvas_user_login_id"=>"jpoulos", "ext_roles"=>"urn:lti:instrole:ims/lis/Administrator,urn:lti:instrole:ims/lis/Instructor,urn:lti:sysrole:ims/lis/SysAdmin,urn:lti:sysrole:ims/lis/User", "launch_presentation_document_target"=>"iframe", "launch_presentation_height"=>"500", "launch_presentation_locale"=>"en", "launch_presentation_return_url"=>"https://jpoulos.instructure.com/courses/837/external_content/success/external_tool_redirect", "launch_presentation_width"=>"500", "lis_person_contact_email_primary"=>"jpoulos@instructure.com", "lis_person_name_family"=>"Poulos", "lis_person_name_full"=>"Jesse Poulos", "lis_person_name_given"=>"Jesse", "lti_message_type"=>"basic-lti-launch-request", "lti_version"=>"LTI-1p0", "oauth_callback"=>"about:blank", "resource_link_id"=>"b1777b696e0fb3ce80bf363f68caa2b2e2f1fb29", "resource_link_title"=>"LTI Test Tool", "roles"=>"urn:lti:instrole:ims/lis/Administrator", "tool_consumer_info_product_family_code"=>"canvas", "tool_consumer_info_version"=>"cloud", "tool_consumer_instance_contact_email"=>"notifications@instructure.com", "tool_consumer_instance_guid"=>"yssK8oDJTJXKw9J62O7BFXy6QGhHkT6kiSt5B8WC", "tool_consumer_instance_name"=>"JPoulos' Sandbox", "user_id"=>"da08341968cb37ba1e522fc7c5ef086b7704eff9", "user_image"=>"https://secure.gravatar.com/avatar/83fe4b875db6af227b73cd1777831cb2?s=128&d=identicon", "oauth_signature"=>"wD7AgdJQ9SftTPEsGocsDbYH2o4="}

  bad_json = {"oauth_consumer_key"=>"badkey", "oauth_signature_method"=>"HMAC-SHA1", "oauth_timestamp"=>"1470694948", "oauth_nonce"=>"n4u2xXQsdfDgsQbmF1YWTCzj8zCIsu3nDvdWxisbo", "oauth_version"=>"1.0", "context_id"=>"b1777b696e0fb3ce80bf363f68caa2b2e2f1fb29", "context_label"=>"asdfasdf", "context_title"=>"stupid_course", "custom_canvas_api_domain"=>"jpoulos.instructure.com", "custom_canvas_course_id"=>"837", "custom_canvas_enrollment_state"=>"", "custom_canvas_user_id"=>"170000004596788", "custom_canvas_user_login_id"=>"jpoulos", "ext_roles"=>"urn:lti:instrole:ims/lis/Administrator,urn:lti:instrole:ims/lis/Instructor,urn:lti:sysrole:ims/lis/SysAdmin,urn:lti:sysrole:ims/lis/User", "launch_presentation_document_target"=>"iframe", "launch_presentation_height"=>"500", "launch_presentation_locale"=>"en", "launch_presentation_return_url"=>"https://jpoulos.instructure.com/courses/837/external_content/success/external_tool_redirect", "launch_presentation_width"=>"500", "lis_person_contact_email_primary"=>"jpoulos@instructure.com", "lis_person_name_family"=>"Poulos", "lis_person_name_full"=>"Jesse Poulos", "lis_person_name_given"=>"Jesse", "lti_message_type"=>"basic-lti-launch-request", "lti_version"=>"LTI-1p0", "oauth_callback"=>"about:blank", "resource_link_id"=>"b1777b696e0fb3ce80bf363f68caa2b2e2f1fb29", "resource_link_title"=>"LTI Test Tool", "roles"=>"urn:lti:instrole:ims/lis/Administrator", "tool_consumer_info_product_family_code"=>"canvas", "tool_consumer_info_version"=>"cloud", "tool_consumer_instance_contact_email"=>"notifications@instructure.com", "tool_consumer_instance_guid"=>"yssK8oDJTJXKw9J62O7BFXy6QGhHkT6kiSt5B8WC", "tool_consumer_instance_name"=>"JPoulos' Sandbox", "user_id"=>"da08341968cb37ba1e522fc7c5ef086b7704eff9", "user_image"=>"https://secure.gravatar.com/avatar/83fe4b875db6af227b73cd1777831cb2?s=128&d=identicon", "oauth_signature"=>"wD7AgdJQ9SftTPEsGocsDbYH2o4="}

  secret = '1'

    test "it should validate the signature" do
      post :receive, good_json
      assert :success
    end
end
