# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 065a8f3130f368da440ba747b3ba4aeaf8149d13af77d16b58b128540d46b389dd9444f95fb83aa3191446409a7e4d081b3343f5cf9e6705f0a13ac9bddf1f0a

test:
  secret_key_base: b8542016f0a44c1c2e89e0088c2d295be0bdad5462f5be224ad172ec26f3718fb4965cd01dd71a607c36096501e6833ece8e7c921acb606205f1387f7a2aa050

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
